version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: football-team-frontend
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - football-team-network

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    profiles:
      - fullstack
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - football-team-network

  teams-service:
    image: teams-service:latest
    container_name: teams-service
    profiles:
      - fullstack
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - football-team-network

networks:
  football-team-network:
    driver: bridge
